#!/usr/bin/env python3
"""Audit the English forms generated by the staging AAC board."""
import re
import sys

HTML = open('my-buddy-test.html', encoding='utf-8').read()
ANCHOR_BLOCK = HTML.split('const ANCHORS = {', 1)[1].split('const ANCHORS2 = {', 1)[0]


def quoted_list(body, name):
    match = re.search(r'\b%s:\[([^]]*)\]' % re.escape(name), body)
    return re.findall(r"'([^']+)'", match.group(1)) if match else []


anchors = {}
for match in re.finditer(r"^\s*(?:'([^']+)'|(\w+)):\s*\{", ANCHOR_BLOCK, re.M):
    name = match.group(1) or match.group(2)
    depth = 1
    pos = match.end()
    while pos < len(ANCHOR_BLOCK) and depth:
        if ANCHOR_BLOCK[pos] == '{':
            depth += 1
        elif ANCHOR_BLOCK[pos] == '}':
            depth -= 1
        pos += 1
    body = ANCHOR_BLOCK[match.end():pos - 1]
    if not name.endswith('_'):
        anchors[name] = {'adjs': quoted_list(body, 'adjs')}

irregular_compare = {
    'far': ('farther', 'farthest'), 'good': ('better', 'best'),
    'bad': ('worse', 'worst'), 'little': ('less', 'least'),
    'much': ('more', 'most'), 'many': ('more', 'most'),
    'fun': ('more fun', 'most fun')
}
more_compare = {'open', 'stuck', 'tired', 'scared', 'careful'}
double_compare = {'big', 'hot', 'sad', 'mad', 'fat', 'thin', 'wet', 'red', 'fun'}


def syllables(word):
    groups = re.findall(r'[aeiouy]+', re.sub(r'e$', '', word.lower()))
    return len(groups) or 1


def compare(word, suffix):
    index = 0 if suffix == 'er' else 1
    if word in irregular_compare:
        return irregular_compare[word][index]
    if word in more_compare:
        return ('more ' if suffix == 'er' else 'most ') + word
    if syllables(word) >= 2 and not word.endswith('y'):
        return ('more ' if suffix == 'er' else 'most ') + word
    if word in double_compare:
        return word + word[-1] + suffix
    if word.endswith('e'):
        return word + suffix[1:]
    if word.endswith('y'):
        return word[:-1] + 'i' + suffix
    return word + suffix


excluded = {'more', 'now', 'mine', 'on', 'off', 'around', 'done', 'careful',
            'gentle', 'comfy', 'hungry', 'thirsty', 'empty'}
generated = []
for page, data in anchors.items():
    for adjective in data['adjs'][:4]:
        if adjective not in excluded:
            generated += [(page, compare(adjective, 'er')),
                          (page, compare(adjective, 'est'))]

adverb_block = HTML.split('const ADVERBS = {', 1)[1].split('};', 1)[0]
adverbs = dict(re.findall(r"(\w+):'([^']+)'", adverb_block))
for page, data in anchors.items():
    if data['adjs'] and data['adjs'][0] in adverbs:
        adverb = adverbs[data['adjs'][0]]
        if adverb != data['adjs'][0]:
            generated.append((page, adverb))

rejected = {
    'openly', 'opener', 'openest', 'tiredly', 'tireder', 'tiredest',
    'scareder', 'scaredest', 'readily', 'thirstily', 'hungrily',
    'stucker', 'stuckest', 'morely', 'bigly', 'funly', 'stillly'
}
failures = ['%s: %s' % item for item in generated if item[1].lower() in rejected]

expected = {
    'open': ('more open', 'most open'), 'tired': ('more tired', 'most tired'),
    'scared': ('more scared', 'most scared'), 'good': ('better', 'best'),
    'little': ('less', 'least')
}
for word, forms in expected.items():
    actual = (compare(word, 'er'), compare(word, 'est'))
    if actual != forms:
        failures.append('%s: %s (expected %s)' % (word, actual, forms))

if not re.search(r'^\s*talk:\s*\{', ANCHOR_BLOCK, re.M):
    failures.append('talk does not have a generated grammar page')

required_text = ['goes', 'going', 'went', 'gone', 'eats', 'eating', 'ate', 'eaten']
for form in required_text:
    if "'" + form + "'" not in HTML and '"' + form + '"' not in HTML:
        failures.append('required irregular or anchor form is not defined: ' + form)

# Every generated level-one doorway page is passed through the same motor-plan
# alignment routine. Keep this guard so a later template edit cannot fix one
# word (such as make) while silently moving the others again.
if HTML.count('return alignHomeWords(out);') < 2:
    failures.append('all anchor page builders must align Home words')

if failures:
    print('GRAMMAR CHECK FAILED')
    for failure in failures:
        print('  - ' + failure)
    sys.exit(1)

print('GRAMMAR CHECK PASSED: %d verb pages, %d generated comparison/adverb forms' %
      (len(anchors), len(generated)))
